/* Total revenue generated by the business */

SELECT
    ROUND(SUM(Revenue), 2) AS total_revenue
FROM online_retail_clean;


/* Total number of unique customers */

SELECT
    COUNT(*) AS total_customers
FROM dim_customer;


/* Top 10 customers based on revenue contribution */

SELECT
    CustomerID,
    ROUND(SUM(Revenue), 2) AS total_revenue
FROM online_retail_clean
GROUP BY CustomerID
ORDER BY total_revenue DESC
LIMIT 10;


/* Top 10 products generating highest revenue */

SELECT
    Description,
    ROUND(SUM(Revenue), 2) AS total_revenue
FROM online_retail_clean
GROUP BY Description
ORDER BY total_revenue DESC
LIMIT 10;


/* Revenue generated from each country */

SELECT
    Country,
    ROUND(SUM(Revenue), 2) AS total_revenue
FROM online_retail_clean
GROUP BY Country
ORDER BY total_revenue DESC;


/* Monthly revenue trend analysis */

SELECT
    Year,
    Month,
    ROUND(SUM(Revenue), 2) AS total_revenue
FROM online_retail_clean
GROUP BY Year, Month
ORDER BY Year, Month;


/* Average revenue per transaction */

SELECT
    ROUND(AVG(Revenue), 2) AS average_order_value
FROM online_retail_clean;


/* Top 5 countries with the highest number of orders */

SELECT
    Country,
    COUNT(DISTINCT InvoiceNo) AS total_orders
FROM online_retail_clean
GROUP BY Country
ORDER BY total_orders DESC
LIMIT 5;